import type { VideoCardProps } from "@/components/video-card"

export const featuredContent = {
  id: "featured-1",
  title: "The Last Kingdom of Acholi",
  description:
    "A powerful documentary exploring the rich history of the Acholi kingdom, from ancient traditions to modern-day cultural preservation. Follow the journey of elders as they share stories passed down through generations, revealing the wisdom and resilience of the Acholi people.",
  image: "/images/hero-featured.jpg",
  category: "Documentary",
  year: "2024",
  rating: "PG-13",
}

export const trendingNow: VideoCardProps[] = [
  {
    id: "trend-1",
    title: "Roots of Gulu",
    image: "/images/roots-of-gulu.jpg",
    year: "2024",
    duration: "1h 45m",
    category: "Drama",
    description: "A young woman returns to Gulu to discover her family's hidden past.",
  },
  {
    id: "trend-2",
    title: "Larakaraka Dance",
    image: "/images/larakaraka.jpg",
    year: "2023",
    duration: "52m",
    category: "Culture",
    description: "The mesmerizing courtship dance of the Acholi people.",
  },
  {
    id: "trend-3",
    title: "Children of the Sun",
    image: "/images/children-sun.jpg",
    year: "2024",
    duration: "2h 10m",
    category: "Drama",
    description: "Three siblings navigate life in post-conflict Northern Uganda.",
  },
  {
    id: "trend-4",
    title: "Echoes of Wang Oo",
    image: "/images/echoes-wangoo.jpg",
    year: "2023",
    duration: "1h 30m",
    category: "Documentary",
    description: "Traditional fireside storytelling traditions.",
  },
  {
    id: "trend-5",
    title: "The Healers",
    image: "/images/healers.jpg",
    year: "2024",
    duration: "1h 55m",
    category: "Documentary",
    description: "Traditional Acholi medicine and spiritual healing practices.",
  },
  {
    id: "trend-6",
    title: "Bwola Royal",
    image: "/images/bwola-royal.jpg",
    year: "2023",
    duration: "45m",
    category: "Culture",
    description: "The sacred royal dance performed for Acholi chiefs.",
  },
]

export const newReleases: VideoCardProps[] = [
  {
    id: "new-1",
    title: "Lakwena Rising",
    image: "/images/lakwena.jpg",
    year: "2025",
    duration: "2h 5m",
    category: "Historical",
    description: "The dramatic story of Alice Lakwena and the Holy Spirit Movement.",
  },
  {
    id: "new-2",
    title: "Pader Dreams",
    image: "/images/pader-dreams.jpg",
    year: "2025",
    duration: "1h 40m",
    category: "Drama",
    description: "A young musician from Pader pursues his dreams against all odds.",
  },
  {
    id: "new-3",
    title: "The Ajaa Market",
    image: "/images/ajaa-market.jpg",
    year: "2025",
    duration: "58m",
    category: "Documentary",
    description: "Daily life in one of Northern Uganda's busiest markets.",
  },
  {
    id: "new-4",
    title: "Luo Legends",
    image: "/images/luo-legends.jpg",
    year: "2025",
    duration: "1h 25m",
    category: "Animation",
    description: "Animated tales from Acholi folklore and mythology.",
  },
  {
    id: "new-5",
    title: "Kitgum Stories",
    image: "/images/kitgum.jpg",
    year: "2025",
    duration: "1h 35m",
    category: "Drama",
    description: "Interconnected stories from the heart of Kitgum district.",
  },
  {
    id: "new-6",
    title: "Rwot's Journey",
    image: "/images/rwot-journey.jpg",
    year: "2025",
    duration: "2h",
    category: "Epic",
    description: "The legendary journey of an ancient Acholi chief.",
  },
]

export const documentaries: VideoCardProps[] = [
  {
    id: "doc-1",
    title: "Rebuilding Home",
    image: "/images/rebuilding.jpg",
    year: "2024",
    duration: "1h 30m",
    category: "Documentary",
    description: "Communities rebuilding after decades of conflict.",
  },
  {
    id: "doc-2",
    title: "The Blacksmiths",
    image: "/images/blacksmiths.jpg",
    year: "2023",
    duration: "48m",
    category: "Documentary",
    description: "Traditional Acholi ironworking and craftsmanship.",
  },
  {
    id: "doc-3",
    title: "Language of Our Fathers",
    image: "/images/language.jpg",
    year: "2024",
    duration: "1h 15m",
    category: "Documentary",
    description: "Preserving the Acholi language for future generations.",
  },
  {
    id: "doc-4",
    title: "Farming the Savannah",
    image: "/images/farming.jpg",
    year: "2023",
    duration: "55m",
    category: "Documentary",
    description: "Agricultural traditions and modern farming in Acholiland.",
  },
  {
    id: "doc-5",
    title: "Voices of Elders",
    image: "/images/elders.jpg",
    year: "2024",
    duration: "1h 42m",
    category: "Documentary",
    description: "Wisdom and stories from Acholi elders.",
  },
  {
    id: "doc-6",
    title: "The Nile's Children",
    image: "/images/nile-children.jpg",
    year: "2024",
    duration: "1h 20m",
    category: "Documentary",
    description: "Life along the Nile in Northern Uganda.",
  },
]

export const musicVideos: VideoCardProps[] = [
  {
    id: "music-1",
    title: "Adungu Melodies",
    image: "/images/adungu.jpg",
    year: "2024",
    duration: "8m",
    category: "Music",
    description: "Traditional harp music performances.",
  },
  {
    id: "music-2",
    title: "Drums of Acholi",
    image: "/images/drums.jpg",
    year: "2024",
    duration: "12m",
    category: "Music",
    description: "Powerful drum ensembles and rhythms.",
  },
  {
    id: "music-3",
    title: "Modern Acholi Beats",
    image: "/images/modern-beats.jpg",
    year: "2025",
    duration: "4m",
    category: "Music",
    description: "Contemporary artists blending tradition with modern sounds.",
  },
  {
    id: "music-4",
    title: "Wedding Songs",
    image: "/images/wedding-songs.jpg",
    year: "2024",
    duration: "15m",
    category: "Music",
    description: "Traditional songs for Acholi wedding ceremonies.",
  },
  {
    id: "music-5",
    title: "Lullabies of Home",
    image: "/images/lullabies.jpg",
    year: "2024",
    duration: "10m",
    category: "Music",
    description: "Gentle songs mothers sing to their children.",
  },
  {
    id: "music-6",
    title: "War Dances",
    image: "/images/war-dances.jpg",
    year: "2023",
    duration: "18m",
    category: "Music",
    description: "Historic warrior dances and chants.",
  },
]

export const categories = [
  { id: "films", name: "Films", count: 45 },
  { id: "documentaries", name: "Documentaries", count: 32 },
  { id: "music", name: "Music Videos", count: 78 },
  { id: "series", name: "Series", count: 12 },
  { id: "culture", name: "Culture & Traditions", count: 56 },
  { id: "historical", name: "Historical", count: 23 },
  { id: "animation", name: "Animation", count: 8 },
  { id: "shorts", name: "Short Films", count: 67 },
]
